# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      react:
        patterns:
          - 'react'
          - 'react-dom'
      tanstack-router:
        patterns:
          - '@tanstack/react-router'
          - '@tanstack/router-plugin'
      tsdown:
        patterns:
          - 'tsdown'
          - '@tsdown/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
        exclude-patterns:
          - '@vitest/eslint-plugin'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
